export default {
  UPDATE_CHART_DATA: 'UPDATE_CHART_DATA',
  ADD_NEW_INSIGHT: 'ADD_NEW_INSIGHT',
  DELETE_INSIGHT: 'DELETE_INSIGHT',
  MOVE_INSIGHT_UP: 'MOVE_INSIGHT_UP',
  MOVE_INSIGHT_DOWN: 'MOVE_INSIGHT_DOWN',
  TOGGLE_VISIBLE_INSIGHT: 'TOGGLE_VISIBLE_INSIGHT',
  REFRESH_THUNDER: 'REFRESH_THUNDER',
  PRELOADER: 'PRELOADER',
};
