export default {
  ADD_NEW_INSIGHT: 'ADD_NEW_INSIGHT',
  MOVE_INSIGHT_UP: 'MOVE_INSIGHT_UP',
  MOVE_INSIGHT_DOWN: 'MOVE_INSIGHT_DOWN',
  TOGGLE_VISIBLE_INSIGHT: 'TOGGLE_VISIBLE_INSIGHT',
  REFRESH_THUNDER: 'REFRESH_THUNDER',
  PRELOADER: 'PRELOADER',
  SET_SELL_EXPAND_COUNTER: 'SET_SELL_EXPAND_COUNTER',
};
