export const GET_INSIGHTS = 'GET_INSIGHTS';
export const SET_INSIGHTS_PENDING = 'SET_INSIGHTS_PENDING';
export const GET_NEW_INSIGHTS = 'GET_NEW_INSIGHTS';
export const UPDATE_INSIGHTS = 'UPDATE_INSIGHTS';
